spring.application.name=analyseur-projet-backend

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/analyseur_db
spring.datasource.username=postgres
spring.datasource.password=ikram

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Groq
groq.api.key=
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile

spring.profiles.include=local